// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health-service.proto

package com.demo.hms.grpc;

public interface HealthMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 memoryUsed = 2;</code>
   */
  int getMemoryUsed();

  /**
   * <code>int32 diskUsed = 3;</code>
   */
  int getDiskUsed();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
