// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health-service.proto

package com.demo.hms.grpc;

public final class HMSService {
  private HMSService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMetricsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMetricsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024health-service.proto\"X\n\rHealthMetrics\022" +
      "\016\n\006status\030\001 \001(\t\022\022\n\nmemoryUsed\030\002 \001(\005\022\020\n\010d" +
      "iskUsed\030\003 \001(\005\022\021\n\ttimestamp\030\004 \001(\003\"\'\n\025Heal" +
      "thMetricsResponse\022\016\n\006status\030\001 \001(\t2N\n\rHea" +
      "lthService\022=\n\021sendHealthMetrics\022\016.Health" +
      "Metrics\032\026.HealthMetricsResponse\"\000B!\n\021com" +
      ".demo.hms.grpcB\nHMSServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HealthMetrics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HealthMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMetrics_descriptor,
        new java.lang.String[] { "Status", "MemoryUsed", "DiskUsed", "Timestamp", });
    internal_static_HealthMetricsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HealthMetricsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMetricsResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
