// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health-service.proto

package com.demo.hms.agent.grpc;

public interface HealthMetricsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMetricsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
